apiVersion: v1
kind: Pod
metadata:
  name: pod-two
  labels:
    app: segundo-pod

spec:
  containers:
    - name: container-pod-two
      image: nginx:latest
      ports:
        - containerPort: 80
