apiVersion: v1
kind: Pod
metadata:
  name: pod-one
  labels:
    app: primeiro-pod

spec:
  containers:
    - name: container-pod-one
      image: nginx:latest
      ports:
        - containerPort: 80
