#kubectl get replicasets
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-deployment

spec:
  template:
    metadata:
      name: portal-pod
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-container
      image: docker.io/aluracursos/portal-noticias:1
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: portal-configmap
      livenessProbe:
        httpGet:
          path: / #alguma rota da aplicação
          port: 80 #porta do container
        periodSeconds: 30 #segundos
        failureThreshold: 3 #Numero de tentivas
        initialDelaySeconds: 50 #atraso inicial para inicar os testes, pois pode estar criando
      readinessProbe:
        httpGet:
          path: /inserir_noticias.php #alguma rota da aplicação
          port: 80 #porta do container
        periodSeconds: 30 #segundos
        failureThreshold: 3 #Numero de tentivas
        initialDelaySeconds: 50 #atraso inicial para inicar os testes, pois pode estar criando
      resources:
        requests:
          cpu: 10m  #10 milicore
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias #deve ser igual ao labels
