#kubectl get replicasets
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-deployment

spec:
  template:
    metadata:
      name: portal-pod
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-container
      image: docker.io/aluracursos/portal-noticias:1
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: portal-configmap
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias #deve ser igual ao labels
