apiVersion: v1
kind: Pod
metadata:
  name: sistema-pod
  labels:
    app: sistema-noticias

spec:
  containers:
    - name: sistema-noticias-container
      image: docker.io/aluracursos/sistema-noticias:1
      ports:
        - containerPort: 80
      envFrom: 
        - configMapRef : 
           name: sistema-configmap  
