apiVersion: v1
kind: Pod
metadata:
  name: database-pod
  labels:
    app: database-noticias

spec:
  containers:
    - name: database-container
      image: docker.io/aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      envFrom: 
        - configMapRef : 
           name: database-configmap